[tools]
gomplate = "4.3.3"
gum = "0.16.2"
helm = "3.19.0"
just = "1.42.4"
k3sup = "0.13.10"
kubelogin = "1.34.0"
node = "22.18.0"
python = "3.12.11"
telepresence = "2.25.0"
uv = "0.8.7"
vault = "1.20.2"
