[tools]
gomplate = "4.3.3"
gum = "0.17.0"
helm = "4.0.4"
just = "1.46.0"
k3sup = "0.13.11"
kubelogin = "1.35.2"
node = "24.13.0"
python = "3.12.12"
telepresence = "2.25.2"
trivy = "0.68.2"
uv = "0.9.25"
vault = "1.21.2"
