apiVersion: v1
kind: Service
metadata:
  name: {{ include "falkordb.fullname" . }}
  labels:
    {{- include "falkordb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
    {{- if .Values.metrics.enabled }}
    - port: 9121
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "falkordb.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "falkordb.fullname" . }}-headless
  labels:
    {{- include "falkordb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "falkordb.selectorLabels" . | nindent 4 }}
